// Manual validation: tests for the resource entry array and resource setter feature.
// This file is NOT auto-generated by generate_validation.py.
//
// Covers:
//   - Compile-time validation of NumResources, m_Resources array size, resource types and slots
//   - Texture_SRV non-array: simple void* + 3-param (baseMip, numMips)
//   - Texture_SRV array:     simple void* + 5-param (baseMip, numMips, baseSlice, numSlices)
//   - Texture_UAV non-array: 2-param (baseMip), numMipLevels hardcoded to 1
//   - Texture_UAV array:     4-param (baseMip, baseSlice, numSlices), numMipLevels hardcoded to 1
//   - Non-texture resources (buffers, RTAS, cbuffers, samplers): simple void* setter only
//   - All ResourceType enum values (except PushConstants) tested in SetterTestInputs
//   - Const-member and wrong-overload compile errors demonstrated in #if 0

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cassert>
#include <windows.h>
#include <DirectXMath.h>

// Generated by srrhi from test_resource_setter.sr:
//   SetterTestInputs with all ResourceType kinds (1 cbuf + 13 SRVs + 8 UAVs + 2 samplers = 24)
#include "test_resource_setter.h"

// Generated by srrhi from test_resource_all_srv.sr:
//   AllSrvInputs with 13 SRV bindings covering all SRV resource kinds
#include "test_resource_all_srv.h"

// Generated by srrhi from test_resource_all_uav.sr:
//   AllUavInputs with 8 UAV bindings covering all UAV resource kinds
#include "test_resource_all_uav.h"

// Generated by srrhi from test_resource_mixed.sr:
//   GBufferPass (1 cbuffer + 2 Texture_SRVs + 1 Texture_UAV)
#include "test_resource_mixed.h"

// Generated by srrhi from test_sampler_only.sr:
//   SamplerOnlyPass (2 samplers, no cbuffers or resources)
#include "test_sampler_only.h"

using namespace srrhi;

// =============================================================================
// COMPILE-TIME VALIDATION: NumResources = NumCBuffers + NumSRVs + NumUAVs + NumSamplers
// =============================================================================

namespace ResourceCountValidation
{
    // SetterTestInputs: 1 cbuffer + 13 SRVs + 8 UAVs + 2 samplers = 24
    static_assert(SetterTestInputs::NumResources == 24u,
        "SetterTestInputs::NumResources must be 1+13+8+2 = 24");

    // AllSrvInputs: 0 cbuffers + 13 SRVs + 0 UAVs + 0 samplers = 13
    static_assert(AllSrvInputs::NumResources == 13u,
        "AllSrvInputs::NumResources must be 13");

    // AllUavInputs: 0 cbuffers + 0 SRVs + 8 UAVs + 0 samplers = 8
    static_assert(AllUavInputs::NumResources == 8u,
        "AllUavInputs::NumResources must be 8");

    // GBufferPass: 1 cbuffer + 2 SRVs + 1 UAV + 0 samplers = 4
    static_assert(GBufferPass::NumResources == 4u,
        "GBufferPass::NumResources must be 1+2+1+0 = 4");

    // SamplerOnlyPass: 0 cbuffers + 0 SRVs + 0 UAVs + 2 samplers = 2
    static_assert(SamplerOnlyPass::NumResources == 2u,
        "SamplerOnlyPass::NumResources must be 0+0+0+2 = 2");
}

// =============================================================================
// COMPILE-TIME VALIDATION: m_Resources[] array size
// =============================================================================

namespace ResourceArraySizeValidation
{
    static_assert(sizeof(SetterTestInputs::m_Resources) == sizeof(srrhi::ResourceEntry) * 24u,
        "SetterTestInputs m_Resources array must have 24 ResourceEntry elements");

    static_assert(sizeof(AllSrvInputs::m_Resources) == sizeof(srrhi::ResourceEntry) * 13u,
        "AllSrvInputs m_Resources array must have 13 ResourceEntry elements");

    static_assert(sizeof(AllUavInputs::m_Resources) == sizeof(srrhi::ResourceEntry) * 8u,
        "AllUavInputs m_Resources array must have 8 ResourceEntry elements");

    static_assert(sizeof(SamplerOnlyPass::m_Resources) == sizeof(srrhi::ResourceEntry) * 2u,
        "SamplerOnlyPass m_Resources array must have 2 ResourceEntry elements");
}

// =============================================================================
// RUNTIME TESTS
// =============================================================================

// Verifies that all resource entries start with nullptr and have correct
// compile-time slots and types immediately after default construction.
static bool TestResourceEntryDefaults()
{
    SetterTestInputs inputs;

    // All pResource pointers must start as nullptr
    for (uint32_t i = 0; i < SetterTestInputs::NumResources; ++i)
        assert(inputs.m_Resources[i].pResource == nullptr);

    // Verify default mip/slice values: baseMipLevel=0, numMipLevels=-1, baseArraySlice=0, numArraySlices=-1
    for (uint32_t i = 0; i < SetterTestInputs::NumResources; ++i)
    {
        assert(inputs.m_Resources[i].baseMipLevel   ==  0);
        assert(inputs.m_Resources[i].numMipLevels   == -1);
        assert(inputs.m_Resources[i].baseArraySlice ==  0);
        assert(inputs.m_Resources[i].numArraySlices == -1);
    }

    // Ordering: [0]=cbuffer, [1..9]=Texture_SRV, [10..13]=non-texture SRV, [14..18]=Texture_UAV, [19..21]=non-texture UAV, [22..23]=Sampler
    assert(inputs.m_Resources[0].type  == srrhi::ResourceType::ConstantBuffer);         // m_Frame       b0
    assert(inputs.m_Resources[1].type  == srrhi::ResourceType::Texture_SRV);            // m_Tex1d       t0
    assert(inputs.m_Resources[2].type  == srrhi::ResourceType::Texture_SRV);            // m_Tex1dArray  t1
    assert(inputs.m_Resources[3].type  == srrhi::ResourceType::Texture_SRV);            // m_Tex2d       t2
    assert(inputs.m_Resources[4].type  == srrhi::ResourceType::Texture_SRV);            // m_Tex2dArray  t3
    assert(inputs.m_Resources[5].type  == srrhi::ResourceType::Texture_SRV);            // m_Tex2dms     t4
    assert(inputs.m_Resources[6].type  == srrhi::ResourceType::Texture_SRV);            // m_Tex2dmsArray t5
    assert(inputs.m_Resources[7].type  == srrhi::ResourceType::Texture_SRV);            // m_Tex3d       t6
    assert(inputs.m_Resources[8].type  == srrhi::ResourceType::Texture_SRV);            // m_TexCube     t7
    assert(inputs.m_Resources[9].type  == srrhi::ResourceType::Texture_SRV);            // m_TexCubeArray t8
    assert(inputs.m_Resources[10].type == srrhi::ResourceType::TypedBuffer_SRV);        // m_TypedBuf    t9
    assert(inputs.m_Resources[11].type == srrhi::ResourceType::StructuredBuffer_SRV);   // m_StructBuf   t10
    assert(inputs.m_Resources[12].type == srrhi::ResourceType::RawBuffer_SRV);          // m_RawBuf      t11
    assert(inputs.m_Resources[13].type == srrhi::ResourceType::RayTracingAccelStruct);  // m_AccelStruct t12
    assert(inputs.m_Resources[14].type == srrhi::ResourceType::Texture_UAV);            // m_RwTex1d     u0
    assert(inputs.m_Resources[15].type == srrhi::ResourceType::Texture_UAV);            // m_RwTex1dArray u1
    assert(inputs.m_Resources[16].type == srrhi::ResourceType::Texture_UAV);            // m_RwTex2d     u2
    assert(inputs.m_Resources[17].type == srrhi::ResourceType::Texture_UAV);            // m_RwTex2dArray u3
    assert(inputs.m_Resources[18].type == srrhi::ResourceType::Texture_UAV);            // m_RwTex3d     u4
    assert(inputs.m_Resources[19].type == srrhi::ResourceType::TypedBuffer_UAV);        // m_RwTypedBuf  u5
    assert(inputs.m_Resources[20].type == srrhi::ResourceType::StructuredBuffer_UAV);   // m_RwStructBuf u6
    assert(inputs.m_Resources[21].type == srrhi::ResourceType::RawBuffer_UAV);          // m_RwRawBuf    u7
    assert(inputs.m_Resources[22].type == srrhi::ResourceType::Sampler);                // m_LinearSampler s0
    assert(inputs.m_Resources[23].type == srrhi::ResourceType::Sampler);                // m_ShadowSampler s1

    // Spot-check slots
    assert(inputs.m_Resources[0].slot  == SetterTestInputs::FrameRegisterIndex);        // b0
    assert(inputs.m_Resources[3].slot  == SetterTestInputs::Tex2dRegisterIndex);        // t2
    assert(inputs.m_Resources[10].slot == SetterTestInputs::TypedBufRegisterIndex);     // t9
    assert(inputs.m_Resources[13].slot == SetterTestInputs::AccelStructRegisterIndex);  // t12
    assert(inputs.m_Resources[16].slot == SetterTestInputs::RwTex2dRegisterIndex);      // u2
    assert(inputs.m_Resources[19].slot == SetterTestInputs::RwTypedBufRegisterIndex);   // u5
    assert(inputs.m_Resources[22].slot == SetterTestInputs::LinearSamplerRegisterIndex);// s0
    assert(inputs.m_Resources[23].slot == SetterTestInputs::ShadowSamplerRegisterIndex);// s1

    printf("  [PASS] Resource entry defaults: nullptr, correct types, correct slots\n");
    return true;
}

// Verifies the simple void* setter for non-texture resources (cbuffer, buffers, samplers)
// AND for texture SRVs (which also have the simple overload, using default mip/slice values).
static bool TestSimpleSetterOverload()
{
    SetterTestInputs inputs;

    int fakeFrame        = 1;
    int fakeTypedBuf     = 2;
    int fakeStructBuf    = 3;
    int fakeRawBuf       = 4;
    int fakeAccelStruct  = 5;
    int fakeRwTypedBuf   = 6;
    int fakeRwStructBuf  = 7;
    int fakeRwRawBuf     = 8;
    int fakeLinearSampl  = 9;
    int fakeShadowSampl  = 10;
    int fakeTex          = 11;

    // Non-texture resources: only have the simple overload
    inputs.SetFrame          (&fakeFrame);
    inputs.SetTypedBuf       (&fakeTypedBuf);
    inputs.SetStructBuf      (&fakeStructBuf);
    inputs.SetRawBuf         (&fakeRawBuf);
    inputs.SetAccelStruct    (&fakeAccelStruct);
    inputs.SetRwTypedBuf     (&fakeRwTypedBuf);
    inputs.SetRwStructBuf    (&fakeRwStructBuf);
    inputs.SetRwRawBuf       (&fakeRwRawBuf);
    inputs.SetLinearSampler  (&fakeLinearSampl);
    inputs.SetShadowSampler  (&fakeShadowSampl);

    assert(inputs.m_Resources[0].pResource  == &fakeFrame);
    assert(inputs.m_Resources[10].pResource == &fakeTypedBuf);
    assert(inputs.m_Resources[11].pResource == &fakeStructBuf);
    assert(inputs.m_Resources[12].pResource == &fakeRawBuf);
    assert(inputs.m_Resources[13].pResource == &fakeAccelStruct);
    assert(inputs.m_Resources[19].pResource == &fakeRwTypedBuf);
    assert(inputs.m_Resources[20].pResource == &fakeRwStructBuf);
    assert(inputs.m_Resources[21].pResource == &fakeRwRawBuf);
    assert(inputs.m_Resources[22].pResource == &fakeLinearSampl);
    assert(inputs.m_Resources[23].pResource == &fakeShadowSampl);

    // Texture SRVs also have the simple overload — it leaves mip/slice at their defaults.
    inputs.SetTex1d    (&fakeTex);  // non-array
    inputs.SetTex2d    (&fakeTex);  // non-array
    inputs.SetTex3d    (&fakeTex);  // non-array
    inputs.SetTex1dArray(&fakeTex); // array
    inputs.SetTex2dArray(&fakeTex); // array

    assert(inputs.m_Resources[1].pResource  == &fakeTex);  // m_Tex1d
    assert(inputs.m_Resources[3].pResource  == &fakeTex);  // m_Tex2d
    assert(inputs.m_Resources[7].pResource  == &fakeTex);  // m_Tex3d
    assert(inputs.m_Resources[2].pResource  == &fakeTex);  // m_Tex1dArray
    assert(inputs.m_Resources[4].pResource  == &fakeTex);  // m_Tex2dArray
    // Mip/slice fields must remain at defaults when using the simple overload
    assert(inputs.m_Resources[3].baseMipLevel   ==  0);
    assert(inputs.m_Resources[3].numMipLevels   == -1);
    assert(inputs.m_Resources[3].baseArraySlice ==  0);
    assert(inputs.m_Resources[3].numArraySlices == -1);

    printf("  [PASS] Simple void* setter works for all non-texture resources and texture SRVs\n");
    return true;
}

// Verifies non-array Texture_SRV 3-param overload (baseMip, numMips)
// and array Texture_SRV 5-param overload (baseMip, numMips, baseSlice, numSlices).
static bool TestTextureSrvMipSliceOverload()
{
    SetterTestInputs inputs;
    int fakeTex = 42;

    // Non-array Texture_SRV: 3-param (baseMip, numMips); baseArraySlice/numArraySlices stay default.
    inputs.SetTex2d(&fakeTex, /*baseMip=*/2, /*numMips=*/3);

    assert(inputs.m_Resources[3].pResource      == &fakeTex);
    assert(inputs.m_Resources[3].baseMipLevel   ==  2);
    assert(inputs.m_Resources[3].numMipLevels   ==  3);
    assert(inputs.m_Resources[3].baseArraySlice ==  0);  // untouched default
    assert(inputs.m_Resources[3].numArraySlices == -1);  // untouched default

    // Array Texture_SRV: 5-param (baseMip, numMips, baseSlice, numSlices).
    inputs.SetTex2dArray(&fakeTex, /*baseMip=*/0, /*numMips=*/-1, /*baseSlice=*/4, /*numSlices=*/2);

    assert(inputs.m_Resources[4].pResource      == &fakeTex);
    assert(inputs.m_Resources[4].baseMipLevel   ==  0);
    assert(inputs.m_Resources[4].numMipLevels   == -1);
    assert(inputs.m_Resources[4].baseArraySlice ==  4);
    assert(inputs.m_Resources[4].numArraySlices ==  2);

    // Non-array Texture_SRV simple unbind followed by 3-param rebind.
    inputs.SetTexCube(nullptr);
    assert(inputs.m_Resources[8].pResource == nullptr);
    inputs.SetTexCube(&fakeTex, 1, -1);
    assert(inputs.m_Resources[8].pResource    == &fakeTex);
    assert(inputs.m_Resources[8].baseMipLevel ==  1);
    assert(inputs.m_Resources[8].numMipLevels == -1);

    printf("  [PASS] Texture_SRV 3-param (non-array) and 5-param (array) setters correct\n");
    return true;
}

// Verifies each of the 9 texture SRV kinds accepts the correct overload:
// non-array types use simple + 3-param; array types use simple + 5-param.
static bool TestAllTextureSrvKindsSetterOverload()
{
    AllSrvInputs inputs;
    int fake = 1;

    // Non-array Texture_SRVs: simple overload + 3-param (baseMip, numMips)
    inputs.SetTex1d       (&fake, 0, -1);   // Texture1D
    inputs.SetTex2d       (&fake, 1,  4);   // Texture2D
    inputs.SetTex2dms     (&fake, 0, -1);   // Texture2DMS
    inputs.SetTex3d       (&fake, 2,  2);   // Texture3D
    inputs.SetTexCube     (&fake, 0, -1);   // TextureCube

    // Array Texture_SRVs: simple overload + 5-param (baseMip, numMips, baseSlice, numSlices)
    inputs.SetTex1dArray  (&fake, 0, -1, 0, -1);  // Texture1DArray
    inputs.SetTex2dArray  (&fake, 0, -1, 2,  3);  // Texture2DArray
    inputs.SetTex2dmsArray(&fake, 0, -1, 0,  4);  // Texture2DMSArray
    inputs.SetTexCubeArray(&fake, 0, -1, 0,  6);  // TextureCubeArray

    for (uint32_t i = 0; i < 9u; ++i)
    {
        assert(inputs.m_Resources[i].pResource == &fake);
        assert(inputs.m_Resources[i].type == srrhi::ResourceType::Texture_SRV);
    }
    // Verify array types have their slice params set
    assert(inputs.m_Resources[3].baseArraySlice == 2);  // tex2dArray
    assert(inputs.m_Resources[3].numArraySlices == 3);
    assert(inputs.m_Resources[8].numArraySlices == 6);  // texCubeArray

    printf("  [PASS] All 9 Texture_SRV kinds accept correct overload (3-param or 5-param)\n");
    return true;
}

// Verifies non-array Texture_UAV 2-param setter (baseMip; numMipLevels hardcoded to 1)
// and array Texture_UAV 4-param setter (baseMip, baseSlice, numSlices; numMipLevels=1).
static bool TestTextureUavFourParamOverload()
{
    SetterTestInputs inputs;
    int fakeUav = 77;

    // Non-array Texture_UAV: 2-param (baseMip only).
    inputs.SetRwTex2d(&fakeUav, /*baseMip=*/3);

    assert(inputs.m_Resources[16].pResource    == &fakeUav);
    assert(inputs.m_Resources[16].baseMipLevel ==  3);
    assert(inputs.m_Resources[16].numMipLevels ==  1);  // always 1 for Texture_UAV

    // Array Texture_UAV: 4-param (baseMip, baseSlice, numSlices).
    inputs.SetRwTex2dArray(&fakeUav, /*baseMip=*/0, /*baseSlice=*/2, /*numSlices=*/4);

    assert(inputs.m_Resources[17].pResource      == &fakeUav);
    assert(inputs.m_Resources[17].baseMipLevel   ==  0);
    assert(inputs.m_Resources[17].numMipLevels   ==  1);  // always 1 for Texture_UAV
    assert(inputs.m_Resources[17].baseArraySlice ==  2);
    assert(inputs.m_Resources[17].numArraySlices ==  4);

    printf("  [PASS] Texture_UAV 2-param (non-array) and 4-param (array) setters correct\n");
    return true;
}

// Verifies each of the 5 texture UAV kinds uses the correct overload:
// non-array uses 2-param (baseMip); array uses 4-param (baseMip, baseSlice, numSlices).
static bool TestAllTextureUavKindsSetterOverload()
{
    AllUavInputs inputs;
    int fake = 2;

    // Non-array Texture_UAVs: 2-param (baseMip)
    inputs.SetRwTex1d (&fake, 0);  // RWTexture1D
    inputs.SetRwTex2d (&fake, 2);  // RWTexture2D
    inputs.SetRwTex3d (&fake, 0);  // RWTexture3D

    // Array Texture_UAVs: 4-param (baseMip, baseSlice, numSlices)
    inputs.SetRwTex1dArray(&fake, 1, 0, -1);  // RWTexture1DArray
    inputs.SetRwTex2dArray(&fake, 0, 4,  2);  // RWTexture2DArray

    for (uint32_t i = 0; i < 5u; ++i)
    {
        assert(inputs.m_Resources[i].pResource    == &fake);
        assert(inputs.m_Resources[i].numMipLevels == 1);
        assert(inputs.m_Resources[i].type         == srrhi::ResourceType::Texture_UAV);
    }
    // Verify array types have their slice params set
    assert(inputs.m_Resources[1].baseMipLevel   == 1);  // rwTex1dArray
    assert(inputs.m_Resources[3].baseArraySlice == 4);  // rwTex2dArray
    assert(inputs.m_Resources[3].numArraySlices == 2);

    printf("  [PASS] All 5 Texture_UAV kinds: 2-param (non-array) or 4-param (array), numMipLevels=1\n");
    return true;
}

// Verifies that non-texture UAV simple setters do NOT write numMipLevels.
static bool TestNonTextureUavSimpleSetterDoesNotWriteMips()
{
    AllUavInputs inputs;

    assert(inputs.m_Resources[5].numMipLevels == -1);  // rwTypedBuffer (TypedBuffer_UAV)
    assert(inputs.m_Resources[6].numMipLevels == -1);  // rwStructBuf   (StructuredBuffer_UAV)
    assert(inputs.m_Resources[7].numMipLevels == -1);  // rwRawBuf      (RawBuffer_UAV)

    int buf = 0;
    inputs.SetRwTypedBuffer(&buf);
    inputs.SetRwStructBuf  (&buf);
    inputs.SetRwRawBuf     (&buf);

    assert(inputs.m_Resources[5].numMipLevels == -1);
    assert(inputs.m_Resources[6].numMipLevels == -1);
    assert(inputs.m_Resources[7].numMipLevels == -1);

    printf("  [PASS] Non-texture UAV simple setters do not write numMipLevels\n");
    return true;
}

// Verifies ResourceType mappings for all 13 SRV kinds in AllSrvInputs.
static bool TestAllSrvResourceTypes()
{
    AllSrvInputs inputs;

    assert(inputs.m_Resources[0].type  == srrhi::ResourceType::Texture_SRV);            // Texture1D
    assert(inputs.m_Resources[1].type  == srrhi::ResourceType::Texture_SRV);            // Texture1DArray
    assert(inputs.m_Resources[2].type  == srrhi::ResourceType::Texture_SRV);            // Texture2D
    assert(inputs.m_Resources[3].type  == srrhi::ResourceType::Texture_SRV);            // Texture2DArray
    assert(inputs.m_Resources[4].type  == srrhi::ResourceType::Texture_SRV);            // Texture2DMS
    assert(inputs.m_Resources[5].type  == srrhi::ResourceType::Texture_SRV);            // Texture2DMSArray
    assert(inputs.m_Resources[6].type  == srrhi::ResourceType::Texture_SRV);            // Texture3D
    assert(inputs.m_Resources[7].type  == srrhi::ResourceType::Texture_SRV);            // TextureCube
    assert(inputs.m_Resources[8].type  == srrhi::ResourceType::Texture_SRV);            // TextureCubeArray
    assert(inputs.m_Resources[9].type  == srrhi::ResourceType::TypedBuffer_SRV);        // Buffer<T>
    assert(inputs.m_Resources[10].type == srrhi::ResourceType::StructuredBuffer_SRV);   // StructuredBuffer<T>
    assert(inputs.m_Resources[11].type == srrhi::ResourceType::RawBuffer_SRV);          // ByteAddressBuffer
    assert(inputs.m_Resources[12].type == srrhi::ResourceType::RayTracingAccelStruct);  // RTAS

    assert(inputs.m_Resources[0].slot  == AllSrvInputs::Tex1dRegisterIndex);
    assert(inputs.m_Resources[9].slot  == AllSrvInputs::TypedBufferRegisterIndex);
    assert(inputs.m_Resources[12].slot == AllSrvInputs::AccelStructRegisterIndex);

    printf("  [PASS] All SRV resource type mappings are correct\n");
    return true;
}

// Verifies ResourceType mappings for all 8 UAV kinds in AllUavInputs.
static bool TestAllUavResourceTypes()
{
    AllUavInputs inputs;

    assert(inputs.m_Resources[0].type == srrhi::ResourceType::Texture_UAV);           // RWTexture1D
    assert(inputs.m_Resources[1].type == srrhi::ResourceType::Texture_UAV);           // RWTexture1DArray
    assert(inputs.m_Resources[2].type == srrhi::ResourceType::Texture_UAV);           // RWTexture2D
    assert(inputs.m_Resources[3].type == srrhi::ResourceType::Texture_UAV);           // RWTexture2DArray
    assert(inputs.m_Resources[4].type == srrhi::ResourceType::Texture_UAV);           // RWTexture3D
    assert(inputs.m_Resources[5].type == srrhi::ResourceType::TypedBuffer_UAV);       // RWBuffer<T>
    assert(inputs.m_Resources[6].type == srrhi::ResourceType::StructuredBuffer_UAV);  // RWStructuredBuffer<T>
    assert(inputs.m_Resources[7].type == srrhi::ResourceType::RawBuffer_UAV);         // RWByteAddressBuffer

    assert(inputs.m_Resources[0].slot == AllUavInputs::RwTex1dRegisterIndex);
    assert(inputs.m_Resources[5].slot == AllUavInputs::RwTypedBufferRegisterIndex);
    assert(inputs.m_Resources[7].slot == AllUavInputs::RwRawBufRegisterIndex);

    printf("  [PASS] All UAV resource type mappings are correct\n");
    return true;
}

// Verifies that the sampler-only srinput has correct resource count, types, and setters.
static bool TestSamplerOnlyPass()
{
    SamplerOnlyPass inputs;

    assert(inputs.m_Resources[0].type == srrhi::ResourceType::Sampler);
    assert(inputs.m_Resources[1].type == srrhi::ResourceType::Sampler);
    assert(inputs.m_Resources[0].slot == SamplerOnlyPass::LinearSamplerRegisterIndex);
    assert(inputs.m_Resources[1].slot == SamplerOnlyPass::ShadowSamplerRegisterIndex);

    int fakeSampler = 0;
    inputs.SetLinearSampler(&fakeSampler);
    inputs.SetShadowSampler(&fakeSampler);

    assert(inputs.m_Resources[0].pResource == &fakeSampler);
    assert(inputs.m_Resources[1].pResource == &fakeSampler);

    printf("  [PASS] Sampler-only pass has correct resource count, types, and setters\n");
    return true;
}

// Verifies GBufferPass: Texture2D SRVs use 3-param (non-array), RWTexture2D UAV uses 2-param.
static bool TestMixedPassResourceOrdering()
{
    GBufferPass inputs;

    // Array ordering: CBuffers first, then SRVs, then UAVs
    // m_Resources[0] = m_Frame    (ConstantBuffer, b0)
    // m_Resources[1] = albedoTex  (Texture_SRV Texture2D, t0)
    // m_Resources[2] = normalTex  (Texture_SRV Texture2D, t1)
    // m_Resources[3] = outputTex  (Texture_UAV RWTexture2D, u0)
    assert(inputs.m_Resources[0].type == srrhi::ResourceType::ConstantBuffer);
    assert(inputs.m_Resources[1].type == srrhi::ResourceType::Texture_SRV);
    assert(inputs.m_Resources[2].type == srrhi::ResourceType::Texture_SRV);
    assert(inputs.m_Resources[3].type == srrhi::ResourceType::Texture_UAV);

    assert(inputs.m_Resources[0].slot == GBufferPass::FrameRegisterIndex);
    assert(inputs.m_Resources[1].slot == GBufferPass::AlbedoTexRegisterIndex);
    assert(inputs.m_Resources[2].slot == GBufferPass::NormalTexRegisterIndex);
    assert(inputs.m_Resources[3].slot == GBufferPass::OutputTexRegisterIndex);

    int fakeFrame  = 0;
    int fakeTex    = 1;
    int fakeOutput = 2;

    inputs.SetFrame     (&fakeFrame);         // cbuffer: simple overload
    inputs.SetAlbedoTex (&fakeTex, 0, -1);   // Texture2D SRV: 3-param (non-array)
    inputs.SetNormalTex (&fakeTex, 2,  4);   // Texture2D SRV: 3-param (non-array)
    inputs.SetOutputTex (&fakeOutput, 1);    // RWTexture2D UAV: 2-param (non-array)

    assert(inputs.m_Resources[0].pResource == &fakeFrame);
    assert(inputs.m_Resources[1].pResource == &fakeTex);
    assert(inputs.m_Resources[2].baseMipLevel == 2);
    assert(inputs.m_Resources[2].numMipLevels == 4);
    assert(inputs.m_Resources[3].pResource    == &fakeOutput);
    assert(inputs.m_Resources[3].baseMipLevel == 1);
    assert(inputs.m_Resources[3].numMipLevels == 1);   // hardcoded to 1 for Texture_UAV

    printf("  [PASS] GBufferPass: correct ordering, simple/3-param/2-param setters all work\n");
    return true;
}

// Verifies that re-binding a resource (calling setter twice) updates correctly.
static bool TestRebindResource()
{
    SetterTestInputs inputs;
    int tex1 = 1, tex2 = 2;

    // Texture2D SRV uses the 3-param overload (non-array)
    inputs.SetTex2d(&tex1, 0, -1);
    assert(inputs.m_Resources[3].pResource == &tex1);

    inputs.SetTex2d(&tex2, 0, -1);
    assert(inputs.m_Resources[3].pResource == &tex2);

    // Unbind via simple overload
    inputs.SetTex2d(nullptr);
    assert(inputs.m_Resources[3].pResource == nullptr);

    printf("  [PASS] Re-binding resource (calling setter multiple times) works correctly\n");
    return true;
}

// Verifies that multiple independent struct instances don't share state.
static bool TestIndependentInstances()
{
    SetterTestInputs inputsA;
    SetterTestInputs inputsB;

    int texA = 10, texB = 20;
    inputsA.SetTex2d(&texA, 0, -1);
    inputsB.SetTex2d(&texB, 0, -1);

    assert(inputsA.m_Resources[3].pResource == &texA);
    assert(inputsB.m_Resources[3].pResource == &texB);
    assert(inputsA.m_Resources[3].pResource != inputsB.m_Resources[3].pResource);

    printf("  [PASS] Independent srinput instances have independent m_Resources[] arrays\n");
    return true;
}

// =============================================================================
// INTENTIONAL COMPILE-ERROR DEMONSTRATIONS (wrapped in #if 0 — do NOT enable)
// =============================================================================
// These blocks document API violations that produce compile errors, proving
// that overload design prevents misuse at compile time.
//
#if 0
void DemoCompileErrors()
{
    SetterTestInputs inputs;
    AllUavInputs     uavInputs;
    int fake = 0;

    // ERROR 1: Texture_SRV non-array SetTex2d does not have a 5-param overload (no slice params).
    //   error C2660: 'SetterTestInputs::SetTex2d': function does not take 5 arguments
    inputs.SetTex2d(&fake, 0, -1, 0, -1);

    // ERROR 2: Texture_SRV array SetTex2dArray does not have a 3-param overload.
    //   error C2660: 'SetterTestInputs::SetTex2dArray': function does not take 3 arguments
    inputs.SetTex2dArray(&fake, 0, -1);

    // ERROR 3: Non-array Texture_UAV SetRwTex2d does not have a 4-param overload.
    //   error C2660: 'SetterTestInputs::SetRwTex2d': function does not take 4 arguments
    inputs.SetRwTex2d(&fake, 0, 0, -1);

    // ERROR 4: Texture_UAV has no simple void* setter.
    //   error C2660: 'SetterTestInputs::SetRwTex2d': function does not take 1 arguments
    inputs.SetRwTex2d(&fake);

    // ERROR 5: Non-texture SRV has no mip/slice setter.
    //   error C2660: 'SetterTestInputs::SetTypedBuf': function does not take 3 arguments
    inputs.SetTypedBuf(&fake, 0, -1);

    // ERROR 6: Non-texture UAV has no mip/slice setter.
    //   error C2660: 'AllUavInputs::SetRwTypedBuffer': function does not take 2 arguments
    uavInputs.SetRwTypedBuffer(&fake, 0);

    // ERROR 7: Cannot modify the const 'slot' field.
    //   error C2166: lvalue specifies const object
    inputs.m_Resources[0].slot = 99u;

    // ERROR 8: Cannot modify the const 'type' field.
    //   error C2166: lvalue specifies const object
    inputs.m_Resources[0].type = srrhi::ResourceType::Sampler;

    // ERROR 9: Cannot copy-assign a ResourceEntry (const members delete the copy-assignment op).
    //   error C2280: attempting to reference a deleted function
    srrhi::ResourceEntry entry = { nullptr, 0u, srrhi::ResourceType::Texture_SRV };
    inputs.m_Resources[0] = entry;
}
#endif  // 0 — intentional compile errors if enabled

// =============================================================================
// MAIN
// =============================================================================

int main()
{
    printf("=== Resource Setter Feature Validation ===\n\n");

    printf("--- Entry Defaults & Compile-time Constants ---\n");
    TestResourceEntryDefaults();

    printf("\n--- Non-texture Setters (simple void*) + Texture SRV simple overload ---\n");
    TestSimpleSetterOverload();

    printf("\n--- Texture_SRV Setters (non-array: simple+3-param | array: simple+5-param) ---\n");
    TestTextureSrvMipSliceOverload();
    TestAllTextureSrvKindsSetterOverload();

    printf("\n--- Texture_UAV Setters (non-array: 2-param | array: 4-param; numMipLevels=1) ---\n");
    TestTextureUavFourParamOverload();
    TestAllTextureUavKindsSetterOverload();

    printf("\n--- Non-texture UAV Behavior ---\n");
    TestNonTextureUavSimpleSetterDoesNotWriteMips();

    printf("\n--- Resource Type Mappings ---\n");
    TestAllSrvResourceTypes();
    TestAllUavResourceTypes();
    TestSamplerOnlyPass();

    printf("\n--- Resource Ordering, Rebinding, Independence ---\n");
    TestMixedPassResourceOrdering();
    TestRebindResource();
    TestIndependentInstances();

    printf("\n=== All resource setter tests PASSED ===\n");
    return 0;
}
