// Manual validation: tests for setter/getter feature and namespace constants.
// This file is NOT auto-generated by generate_validation.py.
// It tests the new class-based cbuffer design with private members + public setters,
// HLSL namespace getters, and per-srinput register index constants.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <windows.h>
#include <DirectXMath.h>

#include "test_scene.h"
#include "test_srinput_basic.h"
#include "test_srinput_multiple.h"
#include "test_setter_types.h"
#include "test_setter_prefix.h"
#include "test_setter_multi.h"

using namespace srrhi;

// =============================================================================
// COMPILE-TIME VALIDATION: namespace constants exist and have correct values
// =============================================================================

namespace ConstantValidation
{
    // test_scene.h: MainInputs namespace
    static_assert(MainInputs::NumCBuffers == 1,
        "MainInputs::NumCBuffers must be 1");
    static_assert(MainInputs::SceneRegisterIndex == 0,
        "MainInputs::SceneRegisterIndex must be 0");

    // test_srinput_basic.h: BasePassInputs namespace
    static_assert(BasePassInputs::NumCBuffers == 2,
        "BasePassInputs::NumCBuffers must be 2");
    static_assert(BasePassInputs::FrameConstsRegisterIndex == 0,
        "BasePassInputs::FrameConstsRegisterIndex must be 0");
    static_assert(BasePassInputs::PassConstsRegisterIndex == 1,
        "BasePassInputs::PassConstsRegisterIndex must be 1");

    // test_srinput_multiple.h: LightingInputs and MaterialInputs namespaces
    static_assert(LightingInputs::NumCBuffers == 2,
        "LightingInputs::NumCBuffers must be 2");
    static_assert(LightingInputs::CameraRegisterIndex == 0,
        "LightingInputs::CameraRegisterIndex must be 0");
    static_assert(LightingInputs::LightRegisterIndex == 1,
        "LightingInputs::LightRegisterIndex must be 1");
    static_assert(MaterialInputs::NumCBuffers == 1,
        "MaterialInputs::NumCBuffers must be 1");
    static_assert(MaterialInputs::MaterialRegisterIndex == 2,
        "MaterialInputs::MaterialRegisterIndex must be 2 (global register across all srinputs)");

    // test_setter_types.h: RendererInputs namespace
    static_assert(RendererInputs::NumCBuffers == 1,
        "RendererInputs::NumCBuffers must be 1");
    static_assert(RendererInputs::BufferRegisterIndex == 0,
        "RendererInputs::BufferRegisterIndex must be 0");

    // test_setter_prefix.h: PrefixInputs namespace
    static_assert(PrefixInputs::NumCBuffers == 1,
        "PrefixInputs::NumCBuffers must be 1");
    static_assert(PrefixInputs::BufferRegisterIndex == 0,
        "PrefixInputs::BufferRegisterIndex must be 0");

    // test_setter_multi.h: SceneInputs (2 cbuffers) + ObjectInputs (1 cbuffer, global reg 2)
    static_assert(SceneInputs::NumCBuffers == 2,
        "SceneInputs::NumCBuffers must be 2");
    static_assert(SceneInputs::FrameRegisterIndex == 0,
        "SceneInputs::FrameRegisterIndex must be 0");
    static_assert(SceneInputs::CameraRegisterIndex == 1,
        "SceneInputs::CameraRegisterIndex must be 1");
    static_assert(ObjectInputs::NumCBuffers == 1,
        "ObjectInputs::NumCBuffers must be 1");
    static_assert(ObjectInputs::ObjectRegisterIndex == 2,
        "ObjectInputs::ObjectRegisterIndex must be 2 (global register)");

} // namespace ConstantValidation

// =============================================================================
// COMPILE-TIME VALIDATION: sizeof for class types (members are private)
// =============================================================================

namespace SizeValidation
{
    static_assert(sizeof(SceneConstants) > 0,   "SceneConstants class must compile");
    static_assert(sizeof(FrameConsts)    > 0,   "FrameConsts class must compile");
    static_assert(sizeof(PassConsts)     > 0,   "PassConsts class must compile");
    static_assert(sizeof(CameraConsts)   > 0,   "CameraConsts class must compile");
    static_assert(sizeof(LightConsts)    > 0,   "LightConsts class must compile");
    static_assert(sizeof(MaterialConsts) > 0,   "MaterialConsts class must compile");
    static_assert(sizeof(TypedBuffer)    > 0,   "TypedBuffer class must compile");
    static_assert(sizeof(PrefixBuffer)   > 0,   "PrefixBuffer class must compile");
    static_assert(sizeof(PerFrameData)   > 0,   "PerFrameData class must compile");
    static_assert(sizeof(PerCameraData)  > 0,   "PerCameraData class must compile");
    static_assert(sizeof(PerObjectData)  > 0,   "PerObjectData class must compile");

} // namespace SizeValidation

// =============================================================================
// RUNTIME TESTS: verify setters compile and can be called correctly
// =============================================================================

static bool TestSceneSetters()
{
    SceneConstants sc;

    // All setter types: const-ref for DirectX types, by-value for scalars
    DirectX::XMFLOAT4X4 identity = {};
    sc.SetView(identity);
    sc.SetProj(identity);
    sc.SetViewProj(identity);
    sc.SetInvViewProj(identity);

    DirectX::XMFLOAT3 pos = {1.0f, 2.0f, 3.0f};
    sc.SetCameraPosWS(pos);

    sc.SetExposure(1.0f);

    DirectX::XMFLOAT4 fog = {0.0f, 100.0f, 0.01f, 0.0f};
    sc.SetFogParams(fog);
    sc.SetFogColor(fog);

    sc.SetFrameNumber(42u);
    sc.SetDeltaTime(0.016f);

    printf("  [PASS] SceneConstants setters compile and run\n");
    return true;
}

static bool TestSrinputBasicSetters()
{
    FrameConsts fc;
    DirectX::XMFLOAT4X4 mat = {};
    fc.SetMatrix(mat);   // m_Matrix -> stripped -> Matrix -> SetMatrix
    fc.SetTime(0.5f);    // m_Time   -> stripped -> Time   -> SetTime

    PassConsts pc;
    pc.SetPassIdx(1u);   // m_PassIdx -> stripped -> PassIdx -> SetPassIdx

    printf("  [PASS] FrameConsts/PassConsts setters compile and run\n");
    return true;
}

static bool TestSrinputMultipleSetters()
{
    CameraConsts cc;
    DirectX::XMFLOAT3 camPos = {0, 0, -5};
    cc.SetPosition(camPos);
    cc.SetFOV(90.0f);

    LightConsts lc;
    DirectX::XMFLOAT3 dir = {0, -1, 0};
    lc.SetDirection(dir);
    lc.SetIntensity(1.0f);

    MaterialConsts mc;
    DirectX::XMFLOAT3 albedo = {0.8f, 0.8f, 0.8f};
    mc.SetAlbedo(albedo);
    mc.SetRoughness(0.3f);

    printf("  [PASS] CameraConsts/LightConsts/MaterialConsts setters compile and run\n");
    return true;
}

static bool TestSetterTypes()
{
    TypedBuffer tb;
    tb.SetScalarFloat(3.14f);
    tb.SetScalarUint(123u);

    DirectX::XMFLOAT3 v3 = {1, 2, 3};
    tb.SetVec3(v3);

    DirectX::XMFLOAT4 v4 = {1, 2, 3, 4};
    tb.SetVec4(v4);

    DirectX::XMFLOAT4X4 mat = {};
    tb.SetMat4x4(mat);

    DirectX::XMINT2 iv2 = {10, 20};
    tb.SetIvec2(iv2);

    printf("  [PASS] TypedBuffer mixed-type setters compile and run\n");
    return true;
}

static bool TestPrefixStripping()
{
    PrefixBuffer pb;
    // m_PrefixedFloat -> PrefixedFloat -> SetPrefixedFloat
    pb.SetPrefixedFloat(1.0f);
    // g_GlobalVec -> GlobalVec -> SetGlobalVec
    DirectX::XMFLOAT3 gv = {1, 2, 3};
    pb.SetGlobalVec(gv);
    // s_StaticCount -> StaticCount -> SetStaticCount
    pb.SetStaticCount(5u);
    // m_WorldMatrix -> WorldMatrix -> SetWorldMatrix
    DirectX::XMFLOAT4X4 wm = {};
    pb.SetWorldMatrix(wm);

    printf("  [PASS] PrefixBuffer prefix-stripping setters compile and run\n");
    return true;
}

static bool TestMultiSrInputSetters()
{
    PerFrameData pfd;
    pfd.SetTime(1.0f);
    pfd.SetDeltaTime(0.016f);
    pfd.SetFrameIndex(100u);

    PerCameraData pcd;
    DirectX::XMFLOAT4X4 m = {};
    pcd.SetViewMatrix(m);
    pcd.SetProjMatrix(m);
    DirectX::XMFLOAT3 cp = {0, 5, -10};
    pcd.SetCameraPos(cp);

    PerObjectData pod;
    pod.SetWorldMatrix(m);
    DirectX::XMFLOAT3 oc = {1, 0, 0};
    pod.SetObjectColor(oc);
    pod.SetRoughness(0.5f);

    printf("  [PASS] Multi-srinput setters compile and run\n");
    return true;
}

// =============================================================================
// INTENTIONAL COMPILE-ERROR DEMONSTRATIONS (wrapped in #if 0 - do NOT enable)
// =============================================================================
// These blocks show what would fail to compile, proving that members are private.
//
#if 0
void DemoCompileErrors()
{
    SceneConstants sc;

    // ERROR 1: Direct private member access - VIEW is private
    // sc.View = DirectX::XMFLOAT4X4{};  // error C2248: 'SceneConstants::View': cannot access private member

    // ERROR 2: offsetof on a class with private members
    // size_t o = offsetof(SceneConstants, View);  // error C2248: access violation on private member

    // ERROR 3: Taking address of private member
    // auto* p = &sc.Exposure;  // error C2248: 'SceneConstants::Exposure': cannot access private member

    // ERROR 4: Wrong setter parameter type - passing wrong type to const-ref setter
    // sc.SetView(1.0f);  // error C2664: cannot convert argument 1 from 'float' to 'const DirectX::XMFLOAT4X4 &'

    // ERROR 5: Wrong setter parameter type - passing non-scalar to scalar setter
    // DirectX::XMFLOAT4X4 mat = {};
    // sc.SetExposure(mat);  // error C2664: cannot convert argument 1 from 'DirectX::XMFLOAT4X4' to 'float'

    // ERROR 6: Calling a non-existent setter (private member naming bypassed)
    // sc.Setview(1.0f);  // error C2039: 'Setview' is not a member of 'SceneConstants'
                           //  (correct is SetView with capital V)
}
#endif // 0 - these would NOT compile if enabled

// =============================================================================
// MAIN
// =============================================================================

int main()
{
    printf("=== Setter/Getter Feature Validation ===\n\n");

    printf("--- Namespace Constants ---\n");
    printf("  MainInputs::NumCBuffers          = %u\n", MainInputs::NumCBuffers);
    printf("  MainInputs::SceneRegisterIndex   = %u\n", MainInputs::SceneRegisterIndex);
    printf("  BasePassInputs::NumCBuffers      = %u\n", BasePassInputs::NumCBuffers);
    printf("  BasePassInputs::FrameConstsRegisterIndex = %u\n", BasePassInputs::FrameConstsRegisterIndex);
    printf("  BasePassInputs::PassConstsRegisterIndex  = %u\n", BasePassInputs::PassConstsRegisterIndex);
    printf("  LightingInputs::NumCBuffers      = %u\n", LightingInputs::NumCBuffers);
    printf("  LightingInputs::CameraRegisterIndex = %u\n", LightingInputs::CameraRegisterIndex);
    printf("  LightingInputs::LightRegisterIndex  = %u\n", LightingInputs::LightRegisterIndex);
    printf("  MaterialInputs::NumCBuffers      = %u\n", MaterialInputs::NumCBuffers);
    printf("  MaterialInputs::MaterialRegisterIndex = %u\n", MaterialInputs::MaterialRegisterIndex);
    printf("  SceneInputs::NumCBuffers         = %u\n", SceneInputs::NumCBuffers);
    printf("  SceneInputs::FrameRegisterIndex  = %u\n", SceneInputs::FrameRegisterIndex);
    printf("  SceneInputs::CameraRegisterIndex = %u\n", SceneInputs::CameraRegisterIndex);
    printf("  ObjectInputs::NumCBuffers        = %u\n", ObjectInputs::NumCBuffers);
    printf("  ObjectInputs::ObjectRegisterIndex= %u\n", ObjectInputs::ObjectRegisterIndex);
    printf("\n");

    printf("--- Setter Tests ---\n");
    TestSceneSetters();
    TestSrinputBasicSetters();
    TestSrinputMultipleSetters();
    TestSetterTypes();
    TestPrefixStripping();
    TestMultiSrInputSetters();
    printf("\n");

    printf("=== All setter/getter tests PASSED ===\n");
    return 0;
}
