// Manual validation: tests for setter/getter feature and namespace constants.
// This file is NOT auto-generated by generate_validation.py.
// It tests the new class-based cbuffer design with private members + public setters,
// HLSL namespace getters, and per-srinput register index constants.

#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <windows.h>
#include <DirectXMath.h>

#include "test_scene.h"
#include "test_srinput_basic.h"
#include "test_srinput_multiple.h"
#include "test_setter_types.h"
#include "test_setter_prefix.h"
#include "test_setter_multi.h"

using namespace srrhi;

// =============================================================================
// COMPILE-TIME VALIDATION: namespace constants exist and have correct values
// =============================================================================

namespace ConstantValidation
{
    // test_scene.h: MainInputs namespace
    static_assert(MainInputs::NumCBuffers == 1,
        "MainInputs::NumCBuffers must be 1");
    static_assert(MainInputs::SceneRegisterIndex == 0,
        "MainInputs::SceneRegisterIndex must be 0");

    // test_srinput_basic.h: BasePassInputs namespace
    static_assert(BasePassInputs::NumCBuffers == 2,
        "BasePassInputs::NumCBuffers must be 2");
    static_assert(BasePassInputs::FrameConstsRegisterIndex == 0,
        "BasePassInputs::FrameConstsRegisterIndex must be 0");
    static_assert(BasePassInputs::PassConstsRegisterIndex == 1,
        "BasePassInputs::PassConstsRegisterIndex must be 1");

    // test_srinput_multiple.h: LightingInputs and MaterialInputs namespaces
    static_assert(LightingInputs::NumCBuffers == 2,
        "LightingInputs::NumCBuffers must be 2");
    static_assert(LightingInputs::CameraRegisterIndex == 0,
        "LightingInputs::CameraRegisterIndex must be 0");
    static_assert(LightingInputs::LightRegisterIndex == 1,
        "LightingInputs::LightRegisterIndex must be 1");
    static_assert(MaterialInputs::NumCBuffers == 1,
        "MaterialInputs::NumCBuffers must be 1");
    static_assert(MaterialInputs::MaterialRegisterIndex == 0,
        "MaterialInputs::MaterialRegisterIndex must be 0 (local register index, reset per srinput scope)");

    // test_setter_types.h: RendererInputs namespace
    static_assert(RendererInputs::NumCBuffers == 1,
        "RendererInputs::NumCBuffers must be 1");
    static_assert(RendererInputs::BufferRegisterIndex == 0,
        "RendererInputs::BufferRegisterIndex must be 0");

    // test_setter_prefix.h: PrefixInputs namespace
    static_assert(PrefixInputs::NumCBuffers == 1,
        "PrefixInputs::NumCBuffers must be 1");
    static_assert(PrefixInputs::BufferRegisterIndex == 0,
        "PrefixInputs::BufferRegisterIndex must be 0");

    // test_setter_multi.h: SceneInputs (2 cbuffers) + ObjectInputs (1 cbuffer, global reg 2)
    static_assert(SceneInputs::NumCBuffers == 2,
        "SceneInputs::NumCBuffers must be 2");
    static_assert(SceneInputs::FrameRegisterIndex == 0,
        "SceneInputs::FrameRegisterIndex must be 0");
    static_assert(SceneInputs::CameraRegisterIndex == 1,
        "SceneInputs::CameraRegisterIndex must be 1");
    static_assert(ObjectInputs::NumCBuffers == 1,
        "ObjectInputs::NumCBuffers must be 1");
    static_assert(ObjectInputs::ObjectRegisterIndex == 0,
        "ObjectInputs::ObjectRegisterIndex must be 0 (local register index, reset per srinput scope)");

} // namespace ConstantValidation

// =============================================================================
// COMPILE-TIME VALIDATION: sizeof for class types (members are private)
// =============================================================================

namespace SizeValidation
{
    static_assert(sizeof(SceneConstants) > 0,   "SceneConstants class must compile");
    static_assert(sizeof(FrameConsts)    > 0,   "FrameConsts class must compile");
    static_assert(sizeof(PassConsts)     > 0,   "PassConsts class must compile");
    static_assert(sizeof(CameraConsts)   > 0,   "CameraConsts class must compile");
    static_assert(sizeof(LightConsts)    > 0,   "LightConsts class must compile");
    static_assert(sizeof(MaterialConsts) > 0,   "MaterialConsts class must compile");
    static_assert(sizeof(TypedBuffer)    > 0,   "TypedBuffer class must compile");
    static_assert(sizeof(PrefixBuffer)   > 0,   "PrefixBuffer class must compile");
    static_assert(sizeof(PerFrameData)   > 0,   "PerFrameData class must compile");
    static_assert(sizeof(PerCameraData)  > 0,   "PerCameraData class must compile");
    static_assert(sizeof(PerObjectData)  > 0,   "PerObjectData class must compile");

} // namespace SizeValidation

// =============================================================================
// RUNTIME TESTS: verify setters compile and can be called correctly
// =============================================================================

static bool TestSceneSetters()
{
    SceneConstants sc;

    // All setter types: const-ref for DirectX types, by-value for scalars
    DirectX::XMFLOAT4X4 identity = {};
    sc.SetView(identity);
    sc.SetProj(identity);
    sc.SetViewProj(identity);
    sc.SetInvViewProj(identity);

    DirectX::XMFLOAT3 pos = {1.0f, 2.0f, 3.0f};
    sc.SetCameraPosWS(pos);

    sc.SetExposure(1.0f);

    DirectX::XMFLOAT4 fog = {0.0f, 100.0f, 0.01f, 0.0f};
    sc.SetFogParams(fog);
    sc.SetFogColor(fog);

    sc.SetFrameNumber(42u);
    sc.SetDeltaTime(0.016f);

    printf("  [PASS] SceneConstants setters compile and run\n");
    return true;
}

static bool TestSrinputBasicSetters()
{
    FrameConsts fc;
    DirectX::XMFLOAT4X4 mat = {};
    fc.SetMatrix(mat);   // m_Matrix -> stripped -> Matrix -> SetMatrix
    fc.SetTime(0.5f);    // m_Time   -> stripped -> Time   -> SetTime

    PassConsts pc;
    pc.SetPassIdx(1u);   // m_PassIdx -> stripped -> PassIdx -> SetPassIdx

    printf("  [PASS] FrameConsts/PassConsts setters compile and run\n");
    return true;
}

static bool TestSrinputMultipleSetters()
{
    CameraConsts cc;
    DirectX::XMFLOAT3 camPos = {0, 0, -5};
    cc.SetPosition(camPos);
    cc.SetFOV(90.0f);

    LightConsts lc;
    DirectX::XMFLOAT3 dir = {0, -1, 0};
    lc.SetDirection(dir);
    lc.SetIntensity(1.0f);

    MaterialConsts mc;
    DirectX::XMFLOAT3 albedo = {0.8f, 0.8f, 0.8f};
    mc.SetAlbedo(albedo);
    mc.SetRoughness(0.3f);

    printf("  [PASS] CameraConsts/LightConsts/MaterialConsts setters compile and run\n");
    return true;
}

static bool TestSetterTypes()
{
    TypedBuffer tb;
    tb.SetScalarFloat(3.14f);
    tb.SetScalarUint(123u);

    DirectX::XMFLOAT3 v3 = {1, 2, 3};
    tb.SetVec3(v3);

    DirectX::XMFLOAT4 v4 = {1, 2, 3, 4};
    tb.SetVec4(v4);

    DirectX::XMFLOAT4X4 mat = {};
    tb.SetMat4x4(mat);

    DirectX::XMINT2 iv2 = {10, 20};
    tb.SetIvec2(iv2);

    printf("  [PASS] TypedBuffer mixed-type setters compile and run\n");
    return true;
}

static bool TestPrefixStripping()
{
    PrefixBuffer pb;
    // m_PrefixedFloat -> PrefixedFloat -> SetPrefixedFloat
    pb.SetPrefixedFloat(1.0f);
    // g_GlobalVec -> GlobalVec -> SetGlobalVec
    DirectX::XMFLOAT3 gv = {1, 2, 3};
    pb.SetGlobalVec(gv);
    // s_StaticCount -> StaticCount -> SetStaticCount
    pb.SetStaticCount(5u);
    // m_WorldMatrix -> WorldMatrix -> SetWorldMatrix
    DirectX::XMFLOAT4X4 wm = {};
    pb.SetWorldMatrix(wm);

    printf("  [PASS] PrefixBuffer prefix-stripping setters compile and run\n");
    return true;
}

static bool TestMultiSrInputSetters()
{
    PerFrameData pfd;
    pfd.SetTime(1.0f);
    pfd.SetDeltaTime(0.016f);
    pfd.SetFrameIndex(100u);

    PerCameraData pcd;
    DirectX::XMFLOAT4X4 m = {};
    pcd.SetViewMatrix(m);
    pcd.SetProjMatrix(m);
    DirectX::XMFLOAT3 cp = {0, 5, -10};
    pcd.SetCameraPos(cp);

    PerObjectData pod;
    pod.SetWorldMatrix(m);
    DirectX::XMFLOAT3 oc = {1, 0, 0};
    pod.SetObjectColor(oc);
    pod.SetRoughness(0.5f);

    printf("  [PASS] Multi-srinput setters compile and run\n");
    return true;
}

// =============================================================================
// RUNTIME TESTS: verify GetRawBytes() returns correct values at correct offsets
// =============================================================================

// Helper: read a T value from raw bytes at a given byte offset.
template<typename T>
static T ReadAt(const uint8_t* bytes, int offset)
{
    T val;
    std::memcpy(&val, bytes + offset, sizeof(T));
    return val;
}

// Verifies that SceneConstants setters write values at the correct byte offsets.
// Offsets are validated by SceneConstantsValidator static_asserts in the header.
static bool TestSceneSetterByteOffsets()
{
    SceneConstants sc;
    const uint8_t* raw = sc.GetRawBytes();

    // SetExposure writes a float at offset 268
    sc.SetExposure(3.14f);
    assert(ReadAt<float>(raw, 268) == 3.14f);

    // SetFrameNumber writes a uint32_t at offset 304
    sc.SetFrameNumber(0xDEADBEEFu);
    assert(ReadAt<uint32_t>(raw, 304) == 0xDEADBEEFu);

    // SetDeltaTime writes a float at offset 308
    sc.SetDeltaTime(0.016f);
    assert(ReadAt<float>(raw, 308) == 0.016f);

    // SetCameraPosWS writes 3 floats at offset 256
    DirectX::XMFLOAT3 pos = {1.0f, 2.0f, 3.0f};
    sc.SetCameraPosWS(pos);
    assert(ReadAt<float>(raw, 256) == 1.0f);
    assert(ReadAt<float>(raw, 260) == 2.0f);
    assert(ReadAt<float>(raw, 264) == 3.0f);

    // SetFogParams writes 4 floats at offset 272
    DirectX::XMFLOAT4 fog = {0.1f, 0.2f, 0.3f, 0.4f};
    sc.SetFogParams(fog);
    assert(ReadAt<float>(raw, 272) == 0.1f);
    assert(ReadAt<float>(raw, 276) == 0.2f);
    assert(ReadAt<float>(raw, 280) == 0.3f);
    assert(ReadAt<float>(raw, 284) == 0.4f);

    printf("  [PASS] SceneConstants setter byte offsets verified via GetRawBytes()\n");
    return true;
}

// Verifies that FrameConsts/PassConsts setters write values at the correct byte offsets.
static bool TestSrinputBasicSetterByteOffsets()
{
    FrameConsts fc;
    const uint8_t* rawFc = fc.GetRawBytes();

    // SetTime writes a float at offset 64
    fc.SetTime(9.99f);
    assert(ReadAt<float>(rawFc, 64) == 9.99f);

    PassConsts pc;
    const uint8_t* rawPc = pc.GetRawBytes();

    // SetPassIdx writes a uint32_t at offset 0
    pc.SetPassIdx(7u);
    assert(ReadAt<uint32_t>(rawPc, 0) == 7u);

    printf("  [PASS] FrameConsts/PassConsts setter byte offsets verified via GetRawBytes()\n");
    return true;
}

// Verifies that TypedBuffer setters write values at the correct byte offsets.
// Offsets are validated by TypedBufferValidator static_asserts in the header.
static bool TestSetterTypesByteOffsets()
{
    TypedBuffer tb;
    const uint8_t* raw = tb.GetRawBytes();

    // SetScalarFloat at offset 0
    tb.SetScalarFloat(2.71828f);
    assert(ReadAt<float>(raw, 0) == 2.71828f);

    // SetScalarUint at offset 4
    tb.SetScalarUint(42u);
    assert(ReadAt<uint32_t>(raw, 4) == 42u);

    // SetVec3 at offset 16 (3 floats)
    DirectX::XMFLOAT3 v3 = {10.0f, 20.0f, 30.0f};
    tb.SetVec3(v3);
    assert(ReadAt<float>(raw, 16) == 10.0f);
    assert(ReadAt<float>(raw, 20) == 20.0f);
    assert(ReadAt<float>(raw, 24) == 30.0f);

    // SetVec4 at offset 32 (4 floats)
    DirectX::XMFLOAT4 v4 = {1.0f, 2.0f, 3.0f, 4.0f};
    tb.SetVec4(v4);
    assert(ReadAt<float>(raw, 32) == 1.0f);
    assert(ReadAt<float>(raw, 36) == 2.0f);
    assert(ReadAt<float>(raw, 40) == 3.0f);
    assert(ReadAt<float>(raw, 44) == 4.0f);

    // SetIvec2 at offset 112 (2 int32_t)
    DirectX::XMINT2 iv2 = {-5, 99};
    tb.SetIvec2(iv2);
    assert(ReadAt<int32_t>(raw, 112) == -5);
    assert(ReadAt<int32_t>(raw, 116) == 99);

    printf("  [PASS] TypedBuffer setter byte offsets verified via GetRawBytes()\n");
    return true;
}

// Verifies that PrefixBuffer setters write values at the correct byte offsets.
static bool TestPrefixStrippingByteOffsets()
{
    PrefixBuffer pb;
    const uint8_t* raw = pb.GetRawBytes();

    // SetPrefixedFloat at offset 0
    pb.SetPrefixedFloat(1.5f);
    assert(ReadAt<float>(raw, 0) == 1.5f);

    // SetStaticCount at offset 16 (after float + padding to vec4 boundary)
    pb.SetStaticCount(99u);
    assert(ReadAt<uint32_t>(raw, 16) == 99u);

    printf("  [PASS] PrefixBuffer setter byte offsets verified via GetRawBytes()\n");
    return true;
}

// Verifies that PerFrameData/PerCameraData/PerObjectData setters write at correct offsets.
static bool TestMultiSrInputSetterByteOffsets()
{
    PerFrameData pfd;
    const uint8_t* rawPfd = pfd.GetRawBytes();

    // SetTime at offset 0
    pfd.SetTime(5.0f);
    assert(ReadAt<float>(rawPfd, 0) == 5.0f);

    // SetDeltaTime at offset 4
    pfd.SetDeltaTime(0.033f);
    assert(ReadAt<float>(rawPfd, 4) == 0.033f);

    // SetFrameIndex at offset 8
    pfd.SetFrameIndex(255u);
    assert(ReadAt<uint32_t>(rawPfd, 8) == 255u);

    PerObjectData pod;
    const uint8_t* rawPod = pod.GetRawBytes();

    // SetRoughness: after a float4x4 (64 bytes) and float3 (12 bytes) = offset 76
    pod.SetRoughness(0.75f);
    assert(ReadAt<float>(rawPod, 76) == 0.75f);

    printf("  [PASS] Multi-srinput setter byte offsets verified via GetRawBytes()\n");
    return true;
}

// =============================================================================
// INTENTIONAL COMPILE-ERROR DEMONSTRATIONS (wrapped in #if 0 - do NOT enable)
// =============================================================================
// These blocks show what would fail to compile, proving that members are private.
//
#if 0
void DemoCompileErrors()
{
    SceneConstants sc;

    // ERROR 1: Direct private member access - VIEW is private
    // sc.View = DirectX::XMFLOAT4X4{};  // error C2248: 'SceneConstants::View': cannot access private member

    // ERROR 2: offsetof on a class with private members
    // size_t o = offsetof(SceneConstants, View);  // error C2248: access violation on private member

    // ERROR 3: Taking address of private member
    // auto* p = &sc.Exposure;  // error C2248: 'SceneConstants::Exposure': cannot access private member

    // ERROR 4: Wrong setter parameter type - passing wrong type to const-ref setter
    // sc.SetView(1.0f);  // error C2664: cannot convert argument 1 from 'float' to 'const DirectX::XMFLOAT4X4 &'

    // ERROR 5: Wrong setter parameter type - passing non-scalar to scalar setter
    // DirectX::XMFLOAT4X4 mat = {};
    // sc.SetExposure(mat);  // error C2664: cannot convert argument 1 from 'DirectX::XMFLOAT4X4' to 'float'

    // ERROR 6: Calling a non-existent setter (private member naming bypassed)
    // sc.Setview(1.0f);  // error C2039: 'Setview' is not a member of 'SceneConstants'
                           //  (correct is SetView with capital V)
}
#endif // 0 - these would NOT compile if enabled

// =============================================================================
// MAIN
// =============================================================================

int main()
{
    printf("=== Setter/Getter Feature Validation ===\n\n");

    printf("--- Namespace Constants ---\n");
    printf("  MainInputs::NumCBuffers          = %u\n", MainInputs::NumCBuffers);
    printf("  MainInputs::SceneRegisterIndex   = %u\n", MainInputs::SceneRegisterIndex);
    printf("  BasePassInputs::NumCBuffers      = %u\n", BasePassInputs::NumCBuffers);
    printf("  BasePassInputs::FrameConstsRegisterIndex = %u\n", BasePassInputs::FrameConstsRegisterIndex);
    printf("  BasePassInputs::PassConstsRegisterIndex  = %u\n", BasePassInputs::PassConstsRegisterIndex);
    printf("  LightingInputs::NumCBuffers      = %u\n", LightingInputs::NumCBuffers);
    printf("  LightingInputs::CameraRegisterIndex = %u\n", LightingInputs::CameraRegisterIndex);
    printf("  LightingInputs::LightRegisterIndex  = %u\n", LightingInputs::LightRegisterIndex);
    printf("  MaterialInputs::NumCBuffers      = %u\n", MaterialInputs::NumCBuffers);
    printf("  MaterialInputs::MaterialRegisterIndex = %u\n", MaterialInputs::MaterialRegisterIndex);
    printf("  SceneInputs::NumCBuffers         = %u\n", SceneInputs::NumCBuffers);
    printf("  SceneInputs::FrameRegisterIndex  = %u\n", SceneInputs::FrameRegisterIndex);
    printf("  SceneInputs::CameraRegisterIndex = %u\n", SceneInputs::CameraRegisterIndex);
    printf("  ObjectInputs::NumCBuffers        = %u\n", ObjectInputs::NumCBuffers);
    printf("  ObjectInputs::ObjectRegisterIndex= %u\n", ObjectInputs::ObjectRegisterIndex);
    printf("\n");

    printf("--- Setter Tests ---\n");
    TestSceneSetters();
    TestSrinputBasicSetters();
    TestSrinputMultipleSetters();
    TestSetterTypes();
    TestPrefixStripping();
    TestMultiSrInputSetters();
    printf("\n");

    printf("--- Setter Byte-Offset Validation (via GetRawBytes()) ---\n");
    TestSceneSetterByteOffsets();
    TestSrinputBasicSetterByteOffsets();
    TestSetterTypesByteOffsets();
    TestPrefixStrippingByteOffsets();
    TestMultiSrInputSetterByteOffsets();
    printf("\n");

    printf("=== All setter/getter tests PASSED ===\n");
    return 0;
}
