// Manual validation: tests for the TextureDimension enum and ResourceEntry::textureDimension.
// This file is NOT auto-generated by generate_validation.py.
//
// Covers:
//   - TextureDimension enum values exist and are correct underlying integers
//   - Every SRV texture kind maps to the correct TextureDimension value
//   - Every UAV texture kind maps to the same TextureDimension as its SRV counterpart
//   - All non-texture resource types (buffers, cbuffers, samplers) map to TextureDimension::None
//   - Mixed srinput: correct dimension assigned to each entry in declaration order
//   - textureDimension is a const field (cannot be modified at runtime)
//   - Compile-error cases shown in #if 0 blocks

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <stdexcept>
#include <windows.h>
#include <DirectXMath.h>

// All texture SRV kinds: AllSrvTextureDimensions (9 SRVs)
#include "test_texture_dimension_srv.h"

// All texture UAV kinds: AllUavTextureDimensions (5 UAVs)
#include "test_texture_dimension_uav.h"

// Non-texture resources: NonTextureResources (1 cbuf + 4 SRVs + 3 UAVs + 1 sampler = 9)
#include "test_texture_dimension_non_texture.h"

// Mixed resources: MixedTextureDimensions (1 cbuf + 3 tex SRV + 1 non-tex SRV + 1 tex UAV + 1 non-tex UAV + 1 sampler = 8)
#include "test_texture_dimension_mixed.h"

// SetterTestInputs: existing comprehensive srinput with all resource kinds
#include "test_resource_setter.h"

#define VALIDATE(expr) \
    do { if (!(expr)) { fprintf(stderr, "FAIL: " #expr "\n"); throw std::runtime_error("Check failed: " #expr); } } while(0)
using namespace srrhi;

// =============================================================================
// COMPILE-TIME VALIDATION: TextureDimension enum values
// =============================================================================

namespace TextureDimensionEnumValidation
{
    // TextureDimension must map to uint32_t
    static_assert(sizeof(srrhi::TextureDimension) == sizeof(uint32_t),
        "TextureDimension must have uint32_t underlying type");

    // None must be 0 (default-constructible without extra init)
    static_assert(static_cast<uint32_t>(srrhi::TextureDimension::None) == 0u,
        "TextureDimension::None must be 0");

    // All enum values must exist and be usable in constant expressions
    constexpr srrhi::TextureDimension td1  = srrhi::TextureDimension::Texture1D;
    constexpr srrhi::TextureDimension td2  = srrhi::TextureDimension::Texture1DArray;
    constexpr srrhi::TextureDimension td3  = srrhi::TextureDimension::Texture2D;
    constexpr srrhi::TextureDimension td4  = srrhi::TextureDimension::Texture2DArray;
    constexpr srrhi::TextureDimension td5  = srrhi::TextureDimension::TextureCube;
    constexpr srrhi::TextureDimension td6  = srrhi::TextureDimension::TextureCubeArray;
    constexpr srrhi::TextureDimension td7  = srrhi::TextureDimension::Texture2DMS;
    constexpr srrhi::TextureDimension td8  = srrhi::TextureDimension::Texture2DMSArray;
    constexpr srrhi::TextureDimension td9  = srrhi::TextureDimension::Texture3D;
    constexpr srrhi::TextureDimension td10 = srrhi::TextureDimension::None;

    // All nine non-None values must be distinct
    static_assert(td1  != td2,  "Texture1D != Texture1DArray");
    static_assert(td1  != td3,  "Texture1D != Texture2D");
    static_assert(td1  != td4,  "Texture1D != Texture2DArray");
    static_assert(td1  != td5,  "Texture1D != TextureCube");
    static_assert(td1  != td6,  "Texture1D != TextureCubeArray");
    static_assert(td1  != td7,  "Texture1D != Texture2DMS");
    static_assert(td1  != td8,  "Texture1D != Texture2DMSArray");
    static_assert(td1  != td9,  "Texture1D != Texture3D");
    static_assert(td1  != td10, "Texture1D != None");
    static_assert(td5  != td6,  "TextureCube != TextureCubeArray");
    static_assert(td7  != td8,  "Texture2DMS != Texture2DMSArray");

} // namespace TextureDimensionEnumValidation

// =============================================================================
// COMPILE-TIME VALIDATION: textureDimension initialized in generated structs
// =============================================================================

namespace TextureDimensionFieldValidation
{
    // Check that AllSrvTextureDimensions has 9 SRVs
    static_assert(AllSrvTextureDimensions::NumSRVs == 9u,
        "AllSrvTextureDimensions must have 9 SRV entries");
    static_assert(AllSrvTextureDimensions::NumResources == 9u,
        "AllSrvTextureDimensions must have 9 total resources (SRVs only)");

    // Check that AllUavTextureDimensions has 5 UAVs
    static_assert(AllUavTextureDimensions::NumUAVs == 5u,
        "AllUavTextureDimensions must have 5 UAV entries");
    static_assert(AllUavTextureDimensions::NumResources == 5u,
        "AllUavTextureDimensions must have 5 total resources (UAVs only)");

    // Check that NonTextureResources has correct counts
    static_assert(NonTextureResources::NumCBuffers  == 1u, "NonTextureResources must have 1 cbuffer");
    static_assert(NonTextureResources::NumSRVs      == 4u, "NonTextureResources must have 4 SRVs");
    static_assert(NonTextureResources::NumUAVs      == 3u, "NonTextureResources must have 3 UAVs");
    static_assert(NonTextureResources::NumSamplers  == 1u, "NonTextureResources must have 1 sampler");
    static_assert(NonTextureResources::NumResources == 9u, "NonTextureResources must have 9 total resources");

    // Check that MixedTextureDimensions has correct counts
    static_assert(MixedTextureDimensions::NumCBuffers  == 1u, "MixedTextureDimensions must have 1 cbuffer");
    static_assert(MixedTextureDimensions::NumSRVs      == 4u, "MixedTextureDimensions must have 4 SRVs");
    static_assert(MixedTextureDimensions::NumUAVs      == 2u, "MixedTextureDimensions must have 2 UAVs");
    static_assert(MixedTextureDimensions::NumSamplers  == 1u, "MixedTextureDimensions must have 1 sampler");
    static_assert(MixedTextureDimensions::NumResources == 8u, "MixedTextureDimensions must have 8 total resources");

} // namespace TextureDimensionFieldValidation

// =============================================================================
// RUNTIME TESTS
// =============================================================================

// Validates every SRV texture kind in AllSrvTextureDimensions.
// Entry order: [0]=Tex1D, [1]=Tex1DArray, [2]=Tex2D, [3]=Tex2DArray,
//              [4]=TexCube, [5]=TexCubeArray, [6]=Tex2DMS, [7]=Tex2DMSArray, [8]=Tex3D
static bool TestSrvTextureDimensions()
{
    AllSrvTextureDimensions inputs;

    // ResourceType: all should be Texture_SRV
    for (uint32_t i = 0; i < AllSrvTextureDimensions::NumResources; ++i)
        VALIDATE(inputs.m_Resources[i].type == srrhi::ResourceType::Texture_SRV);

    // TextureDimension: each matches its HLSL type
    VALIDATE(inputs.m_Resources[0].textureDimension == srrhi::TextureDimension::Texture1D);
    VALIDATE(inputs.m_Resources[1].textureDimension == srrhi::TextureDimension::Texture1DArray);
    VALIDATE(inputs.m_Resources[2].textureDimension == srrhi::TextureDimension::Texture2D);
    VALIDATE(inputs.m_Resources[3].textureDimension == srrhi::TextureDimension::Texture2DArray);
    VALIDATE(inputs.m_Resources[4].textureDimension == srrhi::TextureDimension::TextureCube);
    VALIDATE(inputs.m_Resources[5].textureDimension == srrhi::TextureDimension::TextureCubeArray);
    VALIDATE(inputs.m_Resources[6].textureDimension == srrhi::TextureDimension::Texture2DMS);
    VALIDATE(inputs.m_Resources[7].textureDimension == srrhi::TextureDimension::Texture2DMSArray);
    VALIDATE(inputs.m_Resources[8].textureDimension == srrhi::TextureDimension::Texture3D);

    // None of them should be None
    for (uint32_t i = 0; i < AllSrvTextureDimensions::NumResources; ++i)
        VALIDATE(inputs.m_Resources[i].textureDimension != srrhi::TextureDimension::None);

    printf("  [PASS] All SRV texture kinds have correct TextureDimension values\n");
    return true;
}

// Validates every UAV texture kind in AllUavTextureDimensions.
// RW variants must produce the same TextureDimension as SRV counterparts.
// Entry order: [0]=RwTex1D, [1]=RwTex1DArray, [2]=RwTex2D, [3]=RwTex2DArray, [4]=RwTex3D
static bool TestUavTextureDimensions()
{
    AllUavTextureDimensions inputs;

    // ResourceType: all should be Texture_UAV
    for (uint32_t i = 0; i < AllUavTextureDimensions::NumResources; ++i)
        VALIDATE(inputs.m_Resources[i].type == srrhi::ResourceType::Texture_UAV);

    // TextureDimension: RW variants equal their SRV counterparts
    VALIDATE(inputs.m_Resources[0].textureDimension == srrhi::TextureDimension::Texture1D);     // RWTexture1D
    VALIDATE(inputs.m_Resources[1].textureDimension == srrhi::TextureDimension::Texture1DArray); // RWTexture1DArray
    VALIDATE(inputs.m_Resources[2].textureDimension == srrhi::TextureDimension::Texture2D);      // RWTexture2D
    VALIDATE(inputs.m_Resources[3].textureDimension == srrhi::TextureDimension::Texture2DArray); // RWTexture2DArray
    VALIDATE(inputs.m_Resources[4].textureDimension == srrhi::TextureDimension::Texture3D);      // RWTexture3D

    // None of them should be None
    for (uint32_t i = 0; i < AllUavTextureDimensions::NumResources; ++i)
        VALIDATE(inputs.m_Resources[i].textureDimension != srrhi::TextureDimension::None);

    printf("  [PASS] All UAV texture kinds produce same TextureDimension as SRV counterparts\n");
    return true;
}

// Validates that all non-texture resource types produce TextureDimension::None.
// Entry ordering in NonTextureResources:
//   [0]=cbuffer m_Frame (b0)
//   [1]=Buffer m_TypedBuf (t0)
//   [2]=StructuredBuffer m_StructBuf (t1)
//   [3]=ByteAddressBuffer m_RawBuf (t2)
//   [4]=RaytracingAccelerationStructure m_AccelStruct (t3)
//   [5]=RWBuffer m_RwTypedBuf (u0)
//   [6]=RWStructuredBuffer m_RwStructBuf (u1)
//   [7]=RWByteAddressBuffer m_RwRawBuf (u2)
//   [8]=SamplerState m_Sampler (s0)
static bool TestNonTextureDimensionIsNone()
{
    NonTextureResources inputs;

    // Every entry must have TextureDimension::None
    for (uint32_t i = 0; i < NonTextureResources::NumResources; ++i)
    {
        VALIDATE(inputs.m_Resources[i].textureDimension == srrhi::TextureDimension::None);
    }

    // Double-check by ResourceType
    VALIDATE(inputs.m_Resources[0].type == srrhi::ResourceType::ConstantBuffer);
    VALIDATE(inputs.m_Resources[0].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[1].type == srrhi::ResourceType::TypedBuffer_SRV);
    VALIDATE(inputs.m_Resources[1].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[2].type == srrhi::ResourceType::StructuredBuffer_SRV);
    VALIDATE(inputs.m_Resources[2].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[3].type == srrhi::ResourceType::RawBuffer_SRV);
    VALIDATE(inputs.m_Resources[3].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[4].type == srrhi::ResourceType::RayTracingAccelStruct);
    VALIDATE(inputs.m_Resources[4].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[5].type == srrhi::ResourceType::TypedBuffer_UAV);
    VALIDATE(inputs.m_Resources[5].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[6].type == srrhi::ResourceType::StructuredBuffer_UAV);
    VALIDATE(inputs.m_Resources[6].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[7].type == srrhi::ResourceType::RawBuffer_UAV);
    VALIDATE(inputs.m_Resources[7].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[8].type == srrhi::ResourceType::Sampler);
    VALIDATE(inputs.m_Resources[8].textureDimension == srrhi::TextureDimension::None);

    printf("  [PASS] All non-texture resource types have TextureDimension::None\n");
    return true;
}

// Validates TextureDimension values in MixedTextureDimensions.
// Entry ordering:
//   [0] cbuffer m_Scene        (b0)   -> None
//   [1] Texture2D m_Albedo     (t0)   -> Texture2D
//   [2] Texture2DArray m_ShadowMaps (t1) -> Texture2DArray
//   [3] TextureCube m_EnvMap   (t2)   -> TextureCube
//   [4] StructuredBuffer m_DrawArgs (t3) -> None
//   [5] RWTexture2D m_Output   (u0)   -> Texture2D
//   [6] RWStructuredBuffer m_Counter (u1) -> None
//   [7] SamplerState m_LinearSampler (s0) -> None
static bool TestMixedTextureDimensions()
{
    MixedTextureDimensions inputs;

    VALIDATE(inputs.m_Resources[0].type             == srrhi::ResourceType::ConstantBuffer);
    VALIDATE(inputs.m_Resources[0].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[1].type             == srrhi::ResourceType::Texture_SRV);
    VALIDATE(inputs.m_Resources[1].textureDimension == srrhi::TextureDimension::Texture2D);

    VALIDATE(inputs.m_Resources[2].type             == srrhi::ResourceType::Texture_SRV);
    VALIDATE(inputs.m_Resources[2].textureDimension == srrhi::TextureDimension::Texture2DArray);

    VALIDATE(inputs.m_Resources[3].type             == srrhi::ResourceType::Texture_SRV);
    VALIDATE(inputs.m_Resources[3].textureDimension == srrhi::TextureDimension::TextureCube);

    VALIDATE(inputs.m_Resources[4].type             == srrhi::ResourceType::StructuredBuffer_SRV);
    VALIDATE(inputs.m_Resources[4].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[5].type             == srrhi::ResourceType::Texture_UAV);
    VALIDATE(inputs.m_Resources[5].textureDimension == srrhi::TextureDimension::Texture2D);

    VALIDATE(inputs.m_Resources[6].type             == srrhi::ResourceType::StructuredBuffer_UAV);
    VALIDATE(inputs.m_Resources[6].textureDimension == srrhi::TextureDimension::None);

    VALIDATE(inputs.m_Resources[7].type             == srrhi::ResourceType::Sampler);
    VALIDATE(inputs.m_Resources[7].textureDimension == srrhi::TextureDimension::None);

    printf("  [PASS] Mixed resource srinput: correct TextureDimension per entry\n");
    return true;
}

// Validates TextureDimension on the comprehensive SetterTestInputs
// (1 cbuf + 9 tex SRVs + 4 non-tex SRVs + 5 tex UAVs + 3 non-tex UAVs + 2 samplers = 24).
static bool TestSetterTestInputsDimensions()
{
    SetterTestInputs inputs;

    // [0]  = cbuffer           -> None
    VALIDATE(inputs.m_Resources[0].textureDimension  == srrhi::TextureDimension::None);

    // [1]  = Texture1D         -> Texture1D
    VALIDATE(inputs.m_Resources[1].textureDimension  == srrhi::TextureDimension::Texture1D);
    // [2]  = Texture1DArray    -> Texture1DArray
    VALIDATE(inputs.m_Resources[2].textureDimension  == srrhi::TextureDimension::Texture1DArray);
    // [3]  = Texture2D         -> Texture2D
    VALIDATE(inputs.m_Resources[3].textureDimension  == srrhi::TextureDimension::Texture2D);
    // [4]  = Texture2DArray    -> Texture2DArray
    VALIDATE(inputs.m_Resources[4].textureDimension  == srrhi::TextureDimension::Texture2DArray);
    // [5]  = Texture2DMS       -> Texture2DMS
    VALIDATE(inputs.m_Resources[5].textureDimension  == srrhi::TextureDimension::Texture2DMS);
    // [6]  = Texture2DMSArray  -> Texture2DMSArray
    VALIDATE(inputs.m_Resources[6].textureDimension  == srrhi::TextureDimension::Texture2DMSArray);
    // [7]  = Texture3D         -> Texture3D
    VALIDATE(inputs.m_Resources[7].textureDimension  == srrhi::TextureDimension::Texture3D);
    // [8]  = TextureCube       -> TextureCube
    VALIDATE(inputs.m_Resources[8].textureDimension  == srrhi::TextureDimension::TextureCube);
    // [9]  = TextureCubeArray  -> TextureCubeArray
    VALIDATE(inputs.m_Resources[9].textureDimension  == srrhi::TextureDimension::TextureCubeArray);

    // [10] = Buffer            -> None
    VALIDATE(inputs.m_Resources[10].textureDimension == srrhi::TextureDimension::None);
    // [11] = StructuredBuffer  -> None
    VALIDATE(inputs.m_Resources[11].textureDimension == srrhi::TextureDimension::None);
    // [12] = ByteAddressBuffer -> None
    VALIDATE(inputs.m_Resources[12].textureDimension == srrhi::TextureDimension::None);
    // [13] = RTAS              -> None
    VALIDATE(inputs.m_Resources[13].textureDimension == srrhi::TextureDimension::None);

    // [14] = RWTexture1D        -> Texture1D
    VALIDATE(inputs.m_Resources[14].textureDimension == srrhi::TextureDimension::Texture1D);
    // [15] = RWTexture1DArray   -> Texture1DArray
    VALIDATE(inputs.m_Resources[15].textureDimension == srrhi::TextureDimension::Texture1DArray);
    // [16] = RWTexture2D        -> Texture2D
    VALIDATE(inputs.m_Resources[16].textureDimension == srrhi::TextureDimension::Texture2D);
    // [17] = RWTexture2DArray   -> Texture2DArray
    VALIDATE(inputs.m_Resources[17].textureDimension == srrhi::TextureDimension::Texture2DArray);
    // [18] = RWTexture3D        -> Texture3D
    VALIDATE(inputs.m_Resources[18].textureDimension == srrhi::TextureDimension::Texture3D);

    // [19] = RWBuffer           -> None
    VALIDATE(inputs.m_Resources[19].textureDimension == srrhi::TextureDimension::None);
    // [20] = RWStructuredBuffer -> None
    VALIDATE(inputs.m_Resources[20].textureDimension == srrhi::TextureDimension::None);
    // [21] = RWByteAddressBuffer -> None
    VALIDATE(inputs.m_Resources[21].textureDimension == srrhi::TextureDimension::None);

    // [22] = SamplerState          -> None
    VALIDATE(inputs.m_Resources[22].textureDimension == srrhi::TextureDimension::None);
    // [23] = SamplerComparisonState -> None
    VALIDATE(inputs.m_Resources[23].textureDimension == srrhi::TextureDimension::None);

    printf("  [PASS] SetterTestInputs: all 24 entries have correct TextureDimension\n");
    return true;
}

// Validates that textureDimension is usable in a switch statement (constexpr-friendly).
static bool TestTextureDimensionSwitch()
{
    // Switch on a runtime textureDimension value from a generated entry
    AllSrvTextureDimensions inputs;
    int hitCount = 0;

    for (uint32_t i = 0; i < AllSrvTextureDimensions::NumResources; ++i)
    {
        switch (inputs.m_Resources[i].textureDimension)
        {
            case srrhi::TextureDimension::Texture1D:
            case srrhi::TextureDimension::Texture1DArray:
            case srrhi::TextureDimension::Texture2D:
            case srrhi::TextureDimension::Texture2DArray:
            case srrhi::TextureDimension::TextureCube:
            case srrhi::TextureDimension::TextureCubeArray:
            case srrhi::TextureDimension::Texture2DMS:
            case srrhi::TextureDimension::Texture2DMSArray:
            case srrhi::TextureDimension::Texture3D:
                ++hitCount;
                break;
            case srrhi::TextureDimension::None:
                // Should never reach here for SRV textures
                VALIDATE(false);
                break;
        }
    }

    VALIDATE(hitCount == 9);
    printf("  [PASS] textureDimension is usable in switch statements\n");
    return true;
}

// =============================================================================
// INTENTIONAL COMPILE-ERROR CASES (demonstrated via #if 0 blocks)
//
// These sections show code that must NOT compile because textureDimension is
// declared as 'const' in ResourceEntry, and TextureDimension is a scoped enum.
// =============================================================================

#if 0
// ERROR 1: Attempt to assign to the const textureDimension field.
// Expected error: assignment of read-only member / cannot assign to const member.
static void CompileError_AssignTextureDimension()
{
    AllSrvTextureDimensions inputs;
    // COMPILE ERROR: textureDimension is const — cannot assign a new value.
    inputs.m_Resources[0].textureDimension = srrhi::TextureDimension::Texture2D;
}
#endif

#if 0
// ERROR 2: Attempt to use the unscoped int value as a TextureDimension.
// Expected error: cannot convert 'int' to 'srrhi::TextureDimension'.
static void CompileError_ImplicitIntConversion()
{
    srrhi::TextureDimension dim = 1;  // COMPILE ERROR: no implicit int -> enum class conversion
    (void)dim;
}
#endif

#if 0
// ERROR 3: Attempt to compare a TextureDimension directly against a raw integer.
// Expected error: no match for 'operator==' (TextureDimension vs int).
static void CompileError_CompareWithInt()
{
    AllSrvTextureDimensions inputs;
    if (inputs.m_Resources[0].textureDimension == 1)  // COMPILE ERROR
        printf("should not compile\n");
}
#endif

#if 0
// ERROR 4: Attempt to use ResourceType value where TextureDimension is expected.
// Expected error: cannot convert 'srrhi::ResourceType' to 'srrhi::TextureDimension'.
static void CompileError_WrongEnumType()
{
    srrhi::TextureDimension dim = srrhi::ResourceType::Texture_SRV;  // COMPILE ERROR
    (void)dim;
}
#endif

#if 0
// ERROR 5: Attempt to initialize ResourceEntry without the textureDimension field
// (old 3-field aggregate initializer — now requires 4 const fields).
// Expected error: too few initializers for 'srrhi::ResourceEntry' / missing field.
static void CompileError_OldAggregateInit()
{
    // Old pattern missing textureDimension: { pResource, slot, type }
    srrhi::ResourceEntry e = { nullptr, 0u, srrhi::ResourceType::Texture_SRV };  // COMPILE ERROR
    (void)e;
}
#endif

// =============================================================================
// MAIN
// =============================================================================

int main()
{
    int failures = 0;

    auto run = [&](const char* name, bool(*fn)()) {
        printf("Test: %s\n", name);
        try
        {
            if (!fn())
            {
                fprintf(stderr, "FAIL: %s returned false\n", name);
                ++failures;
            }
        }
        catch (const std::exception& ex)
        {
            fprintf(stderr, "FAIL: %s threw: %s\n", name, ex.what());
            ++failures;
        }
    };

    run("TextureDimension SRV kinds",                      TestSrvTextureDimensions);
    run("TextureDimension UAV kinds (== SRV counterpart)", TestUavTextureDimensions);
    run("Non-texture resources have TextureDimension::None", TestNonTextureDimensionIsNone);
    run("Mixed srinput TextureDimension per entry",         TestMixedTextureDimensions);
    run("SetterTestInputs TextureDimension (all 24)",       TestSetterTestInputsDimensions);
    run("textureDimension usable in switch",                TestTextureDimensionSwitch);

    if (failures == 0)
    {
        printf("\nAll TextureDimension tests PASSED.\n");
        return 0;
    }
    else
    {
        fprintf(stderr, "\n%d TextureDimension test(s) FAILED.\n", failures);
        return 1;
    }
}
